
# ensure we have /opt/deployments directory
- name: ensure /opt/deployments directory exists
  file:
    path: /opt/deployments
    state: directory
    mode: '0755'
  tags:
    - infra-services

- name: Copy docker-compose file to the remote host
  copy:
    src: docker-compose.yml
    dest: /opt/deployments/docker-compose.yml
  tags:
    - infra-services


